const tables=[{id:1,status:'available'},{id:2,status:'occupied',customer:'Juan Dela Cruz'},{id:3,status:'available'},{id:4,status:'reserved',customer:'Maria Santos'},{id:5,status:'occupied',customer:'Juan Dela Cruz'},{id:6,status:'available'},{id:7,status:'available'},{id:8,status:'occupied'},{id:9,status:'available'},{id:10,status:'reserved'},{id:11,status:'available'},{id:12,status:'occupied'}];
const menu=[['Chicken Meal',150,'Meals','https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=700&q=85'],
['Burger Meal',120,'Meals','https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=85'],
['Pasta',130,'Meals','https://images.unsplash.com/photo-1626844131082-256783844137?auto=format&fit=crop&w=700&q=85'],
['Carbonara',140,'Meals','https://images.unsplash.com/photo-1727005217349-66276af3aa7d?auto=format&fit=crop&w=700&q=85'],
    ['Iced Coffee',90,'Drinks','https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=700&q=85'],
    ['Fries',80,'Snacks','https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=700&q=85'],
    ['Leche Flan',60,'Desserts','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU01gp3iiaKJ6RAXE1bxqLPAD6JJEZBEw2V4og61STIg&s=10']];
const customers=[['Maria Santos','09XX XXX 1111','Table 04'],['Juan Dela Cruz','09XX XXX 2222','Table 05'],
['Anna Reyes','09XX XXX 3333','Table 02']];let reservations=[['7:00 PM','Maria Santos','Table 04','4 guests'],
['8:00 PM','John Reyes','Table 08','2 guests'],['10:00 PM','Liza Mercado','Table 09','3 guests']];let cart=[],currentTable=5;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],peso=n=>'₱'+n.toLocaleString('en-PH');
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
function counts(){$('#available').textContent=tables.filter(x=>x.status==='available').length;$('#occupied').textContent=tables.filter(x=>x.status==='occupied').length;$('#reserved').textContent=tables.filter(x=>x.status==='reserved').length;$('#total').textContent=tables.length}
function card(t){return `<div class="table" onclick="openTable(${t.id})"><b>T${String(t.id).padStart(2,'0')}</b><span class="${t.status}">${t.status}</span></div>`}
function renderTables(){counts();$('#dashTables').innerHTML=tables.slice(0,6).map(card).join('');let q=($('#search').value||'').replace(/[^0-9]/g,'');let f=$('#filter').value;$('#allTables').innerHTML=tables.filter(t=>(f==='all'||t.status===f)&&(!q||String(t.id).includes(q))).map(card).join('')}
function page(p){$$('.page').forEach(x=>x.classList.add('hidden'));$('#'+p).classList.remove('hidden');$('#title').textContent={dashboard:'Dashboard',tables:'Tables',detail:'Table Details',orders:'New Order',billing:'Billing',customers:'Customers',reservations:'Reservations',settings:'Settings'}[p]||'Dashboard';if(p==='orders')renderMenu();if(p==='customers')renderCustomers();if(p==='reservations')renderReservations()}
function openTable(id){currentTable=id;let t=tables.find(x=>x.id===id);$('#detailName').textContent='Table '+String(id).padStart(2,'0');$('#detailStatus').textContent=t.status;$('#detailStatus').className='pill '+t.status;$('#detailCustomer').textContent=t.customer||'No customer';$('#detailGuests').textContent=t.status==='occupied'?'4':'—';$('#orderTable').textContent=String(id).padStart(2,'0');$('#detailOrder').innerHTML=t.status==='occupied'?'<div class="row"><span>Chicken Meal ×2</span><b>₱300</b></div><div class="row"><span>Iced Coffee ×1</span><b>₱90</b></div><div class="row"><span>Fries ×1</span><b>₱80</b></div>':'<p style="font-size:9px;color:#8994a4">No current order.</p>';page('detail')}
function renderMenu(list=menu){$('#menu').innerHTML=list.map(m=>{let i=menu.indexOf(m);return `<div class="food"><div class="food-img" style="background-image:url('${m[3]}')"></div><div class="food-info"><b>${m[0]}</b><span>${peso(m[1])}</span><button onclick="add(${i})">＋ Add</button></div></div>`}).join('')}
function add(i){cart.push(menu[i]);renderCart();toast(menu[i][0]+' added')}
function renderCart(){$('#cartCount').textContent=cart.length+' item'+(cart.length===1?'':'s');$('#cartItems').innerHTML=cart.map(x=>`<div class="row"><span>${x[0]}</span><b>${peso(x[1])}</b></div>`).join('')||'<p style="font-size:9px;color:#8994a4">No items added.</p>';$('#cartTotal').textContent=peso(cart.reduce((a,x)=>a+x[1],0))}
function renderCustomers(){$('#customersList').innerHTML=customers.map((c,i)=>`<div class="cust" onclick="profile(${i})"><b>${c[0]}</b><span>${c[1]} · ${c[2]}</span></div>`).join('');profile(0)}function profile(i){let c=customers[i];$('#profile').innerHTML=`<h3>${c[0]}</h3><p style="font-size:9px;color:#8994a4">${c[1]}</p><div class="row"><span>Current Table</span><b>${c[2]}</b></div><div class="row"><span>Total Visits</span><b>5</b></div>`}
function renderReservations(){$('#resList').innerHTML=reservations.map((r,i)=>`<div class="reservation"><strong>${r[0]}</strong><div><h4>${r[1]}</h4><p>${r[2]} · ${r[3]}</p></div><button onclick="cancelRes(${i})">Cancel</button></div>`).join('')||'<div class="card">No reservations.</div>'}
function cancelRes(i){let r=reservations[i];$('#modalText').innerHTML=`Cancel the reservation for <b>${r[1]}</b>?<br>${r[0]} · ${r[2]} · ${r[3]}`;$('#modal').classList.remove('hidden');$('#confirm').onclick=()=>{reservations.splice(i,1);$('#modal').classList.add('hidden');renderReservations();toast('Reservation cancelled')}}
$('#loginForm').onsubmit=e=>{e.preventDefault();$('#login').classList.add('hidden');$('#app').classList.remove('hidden');toast('Welcome to DineFlow')};
$$('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));$('#bell').onclick=()=>toast('No new notifications');$('#search').oninput=renderTables;$('#filter').onchange=renderTables;$('#addTable').onclick=()=>{tables.push({id:tables.length+1,status:'available'});renderTables();toast('Table added')};
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');let c=b.textContent.trim();renderMenu(c==='All'?menu:menu.filter(x=>x[2]===c))});
$('#place').onclick=()=>{if(!cart.length)return toast('Add an item first');let t=tables.find(x=>x.id===currentTable);t.status='occupied';t.customer='Juan Dela Cruz';toast('Order placed');cart=[];renderCart();renderTables();page('detail')};$('#payNow').onclick=()=>{let t=tables.find(x=>x.id===currentTable);t.status='available';delete t.customer;renderTables();toast('Payment confirmed');page('tables')};
$('#newRes').onclick=()=>{$('#modalTitle').textContent='New Reservation';$('#modalText').innerHTML='Use the reservation details form to add a guest reservation.';$('#confirm').textContent='Add Reservation';$('#modal').classList.remove('hidden');$('#confirm').onclick=()=>{reservations.push(['6:30 PM','New Guest','Table 01','2 guests']);$('#modal').classList.add('hidden');$('#confirm').textContent='Cancel Reservation';renderReservations();toast('Reservation added')}};$('#close').onclick=$('#keep').onclick=()=>{$('#modal').classList.add('hidden');$('#confirm').textContent='Cancel Reservation'};$('#save').onclick=()=>toast('Settings saved');
renderTables();
